### PR TITLE
fix: Support for TypeDoc 0.16

### PR DESCRIPTION
**Pull request by Gerrit0**
TypeDoc 0.16 changed how programmatic API users should set up an application

https://github.com/TypeStrong/typedoc/releases/tag/v0.16.0

### CODE REVIEW

**Comment by Gerrit0** [comment]
I also enabled excludeDeclarations + ignoreCompilerErrors in the tests as it provides a ~25% speed boost.

**Comment by rogierschouten** [comment]
@Gerrit0  thank you so much!!  I wasn't aware of this.  

One question: do you have time to maybe remove the parseFloat? It might work, but comparing floating-point number is hazardous in general due to the way IEEE floating points are represented in computers.  Simply use either the semver package or split the string by dots and use two parseInts?

**Comment by Gerrit0** [comment]
Considering the release has been out for all of an hour, no surprise there ;)

I really didn't want to break the API, but it was either this or hack together a worse solution. PR updated.

**Comment by rogierschouten** [comment]
thank you @Gerrit0 ,  I will publish a release tonight if I can make it, otherwise tomorrow night

**Comment by rogierschouten** [comment]
btw I saw you also had to change the test - should I make this a semver-major release then?

**Comment by Gerrit0** [comment]
The surface of your API hasn't changed (well, except in so far as some changes to TypeDoc's option parsing have changed it...).

TypeDoc itself isn't at a stable point in semver yet, it's up to you.

**Comment by rogierschouten** [comment]
published 2.2.4.  Thank you very much!

**Pull request merged**
