### PR TITLE
Work with clean copy of user options

### PR DESCRIPTION
**Pull request by tristan00b**
Fix for #44.

### CODE REVIEW

**Comment by rogierschouten** [comment]
Hi @tristan00b  good idea to make a clean copy, this is the right direction.  

Question:  your JSON.parse(JSON.stringify is not a clean copy.  the JSON format does not support all types of strings, and e.g. it maps null and undefined to a single value.  Is there a less risky way of making this copy?   

I myself haven't been programming for two years so I don't know what the current best practice is; however I am pretty sure it is not that way. Can you check and see if you can find a better way?

**Comment by rogierschouten** [comment]
Actually, should it be a  shallow copy, not a deep copy for all options?  That Typedoc option map is so deep I am not sure there isn't something with a function type in there which would get destroyed...

**Comment by tristan00b** [comment]
@rogierschouten Good point! In that case, I think `Object.assign` or should suffice, as long as the only thing `gulp-typedoc` needs to to is add the default logger. What do you think?

**Comment by rogierschouten** [comment]
@tristan00b  sounds good

**Comment by tristan00b** [comment]
@rogierschouten Sorry, I'm not very familiar with doing GitHub PR's, so I don't know what kind of notifications you get. But the branch is ready for merging. Cheers!

**Comment by rogierschouten** [comment]
published as v3.0.2
Thank you @tristan00b !

**Comment by tristan00b** [comment]
@rogierschouten And thank you as well!

**Pull request merged**
